### ISSUE TITLE
Luis Narvaez Identify all engines names, logs files locations databases used and config files

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#102]
still missing 1 x column per required quesrtion bellow:

where is the config file to manage the engine?
which dependencies with other engine at cofig file level ,network or system?
Identify comsuption in RAM and CPU and hdd
Identify if use a DB underline or not
Identify if repo updates and installation are centralized or not

**Comment by samy-mohsen** [comment]
@k1ktr0n I can not understand the task. Can you give me more specific details about what I'm supposed to do exactly?
Did you mean that you want me to redocument some of the existing documentations or what?

**Comment by SibirskiyVolk** [comment]
C. What information are required to create each plugin one service
   a. plugin name
b. plugin description
c. plugin dependencies (are there any other plugins that are required to install this)
d. plugin dependants (are there any other plugins that require this plugin to install)
e. plugin packages (what packages are required to be pre-installed in order to run this plugin)
f. plugin packages repositories (what deb repositories are required to install the packages)
g. plugin install script (a standalone script that runs and does the installation part including downloading and compiling from sourcecode)
h. plugin remove script (a standalone script that removes the plugin without its’ dependants as well as removing config files for it.
I. configuration files for the plugin listed and sorted by package
j. data to be edited for each config file by user
k. parameters or arguments to be set by the user for the config files
l. start/stop script for plugin
m. directories used by each plugin (example: owncloud stores user files in /home/x/y/z)
n. GUI files for the plugin (CSS/HTML/JS)
o. Backend scripts to handle the GUI requests

**Comment by k1ktr0n** [comment]
What is the relation within plugin and the requested task?

**Comment by SibirskiyVolk** [comment]
because every service is a portable plugin that can updated and fixed and edited and tested separately 
for example: suricata serivce is a plugin
friendica service is a plugin
and packages like nginx is part of the core plugin because it's essential to the core function of the system


part of the documentation that I am working on:

A. Why plugin based installation
Mainly because it enables us to have a free distribution model of the system with core plugins only and save the more advanced plugins as the paid product

Not only this. But using this approach we can have early releases and continue the development of the platform adding more features with the product already available at the customer’s home or office. This helps get the product out in the market earlier than the current approach.

This approach also helps organize and guide the development process as we’ll not only be limited to our internal team but also give the power to third party developers and opensource communities to submit plugins that users request as features.

B. How much effort we’ll have to spend in order to adopt this approach
This approach would only require minimal time and effort to adopt from the current approach . Since it only requires information that we’ll have to collect anyway in order to write the backend for the UI … for example we’ll always need to know the config file for different services in order to be able to modify them.

**Comment by k1ktr0n** [comment]
Then you can start to identify core services and plugins please by using the LAB with installed scripts.
You can add pending engines like : 
ndpi
hstsbypasser
bankbypasser
broids,vortex,and many others not implemented and in pending issues

**Comment by mariacrangel** [comment]
# Platform Dependencies
For installing Librerouter, before you ought to install some of Operative Systems:  Ubuntu 12.04, Ubuntu 14.04, Debian GNU/Linux 7, Debian GNU/Linux 8, Trisquel 7.

After You've have selected the Operative System of your preference and cover all the  requirements for installing librerouter, the next step is to run the installation script, this installation script `LibreKernel/app-installation-script.sh` is in libreroter Github repository.

You can download the installation script (`app-installation-script.sh`) from the repository https://github.com/Librerouter/Librekernel.git  or you can check in the `Readme.md` file the Resume of steps and executing steps.
- `apt-get install curl` 
- `curl -L http://bit.ly/2gbKstn | bash`

Personally after I read the Readme.md file I downloaded the installation  script to check how it works.
You can execute  the installation  script writing  `./app-installation-script.sh` in a terminal.
The first thing that  the script does is check installation requirements like Operative System or Platform, Detecting Hardware,   number of Ethernet Interfaces, Internet Access, Physical Memory Size and root Partition Size.
The script establish the Internet connection on one of the  interfaces and set another one as an internal interface.
The next is to install ntpdate to sync Time. Then Prepare Debian repository, before installing this you need to install `apt-transport-https`.
Once apt-transport-https is installed the script prepares other repositories: owncloud, prosody, tahoe, yacy, i2p, tor, Webmin,  kibana, Logstash, elastic, backports. The repositories will prepare according to version of Operative System selected. then the repository is updated and continues to  install  libraries and tools.

# List of libs, Engines, and Tools that Integrate the Platform

**Comment by orwellencarnation** [comment]
https://github.com/Librerouter/Librekernel/blob/gh-pages/Engines%20Logfiles%20Configuration%20Files%20and%20Resources

**Comment by orwellencarnation** [comment]
1 x column per required quesrtion bellow:
where is the config file to manage the engine?
which dependencies with other engine at cofig file level ,network or system?
Identify comsuption in RAM and CPU and hdd
Identify if use a DB underline or not
Identify if repo updates and installation are centralized or not
