### ISSUE TITLE
Decided which base operating system we use

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#11]
Libre WRT
Devuan Dont boot in Pipo tested version 32 and 64 bits
Alpine : Same
Uruk: Boots good but we dont need probably the ALL desktop environment and just x11 no idea if will be maintained.
Linux Linux from Scratch version ipfire
from Scratch version our own debian
fromm Scratch version our own freebsd

**Comment by rcdeoliveira** [comment]
There is some documentation[1] about Debian on Pipo X8, but the test was performed on March 2016 with Debian Testing (Stretch). Actually, I tried to compile Goodix driver on kernel 3.16 and it didn't work (looking on kernel source 3.16, this driver didn't exist).
I will try to compile a vanilla kernel 4.7 to use it on Debian Jessie.

[1] https://wiki.debian.org/InstallingDebianOn/PIPO/PIPO%20X8

**Comment by neeveecomm** [comment]
whether librewrt will boot up in pipo X8, as it seems that librewrt is targeted for MIPS processor

**Comment by rcdeoliveira** [comment]
I was trying few things, jessie-backports has available the kernel 4.6. To install it, a line referring to jessie-backports has to be added to sources:
`echo deb http://ftp.es.debian.org/debian/ jessie-backports main
 > /etc/apt/sources.list.d/jessie-backports.list`

After a repo update could be installed with:
`apt install linux-headers-4.6.0-0.bpo.1-amd64/jessie-backports linux-image-4.6.0-0.bpo.1-amd64/jessie-backports`

I will try to compile the driver for the touchscreen (goodix) with the recipe from Wiki Debian.

**Comment by sandeep-mvd** [comment]
I did not work much on network OS. I have not used network OS like ipfire etc.. Therefore I am not sure how much time will be needed in porting them to Pipo X8.  As I lack such knowledge, I think my comments might not be the best suggestion. But Please let me know if this makes sense.

Because we do not need complete features from OS like Uruk, it will be better to take a debian Linux, make it as much thin as possible(disable unneeded configs) and port it first. Then add only the needed components from the best available sources. This way I think we will have much controle about what are we including in our SW and whether they will be maintained or not.
