### ISSUE TITLE
 Physical reboot 	Disable control+alt+del on inittab & /​etc/​acpi/​powerbtn-acpi-support.sh

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#173]
http://www.ducea.com/2006/06/20/how-to-disable-ctrl-alt-del-from-rebooting-a-linux-system/

**Comment by fjmz** [comment]
Fixed and checked, any can check too?

The commit: https://github.com/Librerouter/Librekernel/commit/926747113ed24f54cbe70c6387f15e1a48393bcf

**Comment by fjmz** [comment]
Thanks Luis, I forgot to add the button.
Gracias Luis, se me olvidó añadir lo del boton.

**Comment by fjmz** [comment]
Another thing, the file you uploaded (ctrl-alt-del.target) is not necessary, since systemd takes care of everything and the file is uploaded but NOT used at all, I proceed to remove it. A greeting.

Otra cosa más, el archivo que has subido (ctrl-alt-del.target) no es necesario, ya que systemd se encarga de todo y el archivo esta subido pero NO se usa para nada, procedo a eliminarlo. Un saludo.

**Comment by orwellencarnation** [comment]
whats the result them here put a resume of whats working and whats not

**Comment by luisnarvaez19** [comment]
Francisco add the ctrl-alt-del solution and I added the power acpi solution. The issue is complete and It works fine.
