### ISSUE TITLE
Luis Narvaez/fjmz Fail2Ban

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#174]
Its fail2ban implemented?

**Comment by fjmz** [comment]
Are there any exceptions? If there is not, I can start implementing it.

**Comment by orwellencarnation** [comment]
what you mean by exception?

**Comment by fjmz** [comment]
I would like to know if I should implement it for any address and any service or not.
Obviously, for the services that exist today.

**Comment by pastafaarian** [comment]
no exception

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique

**Comment by fjmz** [comment]
Implemented, some filters are disabled due to several problems, such as with sogo, which currently has an open issue. (number 190)

**Comment by orwellencarnation** [comment]
the only guy close issues is me, where you implemented? I SEE NO COMMIT

**Comment by fjmz** [comment]
It is installed and configured, there were some filters that could not be applied because things that belong to other issues fail.

The commit was not added because I did not have permissions at that time, you can check the code to verify that it is installed and with a partial configuration, since there are services that are not yet implemented or do not work correctly.

The changes was pulled u can check: https://github.com/Librerouter/Librekernel/pull/192 and https://github.com/Librerouter/Librekernel/pull/191

**Comment by orwellencarnation** [comment]
its not implemented in app installation script

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique

**Comment by fjmz** [comment]
Done 4 DAYS ago.

https://github.com/fjmz/Librekernel/commit/cfa734087fc9a1a867308cc54dc394cbaefc6b09

Regards.

**Comment by orwellencarnation** [comment]
thanks and sorry

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
