### ISSUE TITLE
HSTS BYPASS for Chrome,Firefox,Opera,Edge browsers

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#18]
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

Some sites like google.com, dropbox.com are HSTS. This means that browser has certificated for these sites in its mind (by default). So we are not able to redirect HSTS sited because browser will show certificate error without "Add exception(get certificate)" option.

Modify a series of toolset and scripts that now exist in ruby and python modify existing code in ruby and python to perform an additional or special function after downgrading from https to http. What is redirecting hard to another web page:

Usually hsts is embedded in all browsers and the hsts bypass works like this:
Https domain X ------> http y.x ------>

We want to redesign the system architecture:
Https domain X ------> http y.x ------> redirection hard ------> http z ------> https z

The tools used are:

Mitmf bettercap sslstrip sslslip "pythem" dns2proxy dnschef spiderlabs ZackAttack
Hsts bypassing "sslstrip" "pythen" "bettercap" "dns2proxy"

The architecture is fully documented yet reengineering is necessary:
Type in google images: "hsts bypass"
Now do the same on google.com and read the first links.

**Comment by nikdavnik** [comment]
I tryed to bypass HSTS with sslstrip2 + dns2proxy. 
What I got is

HOW SSLSTRIP2/DNS2PROXY WORKS ?

* The user goes on google.com 
* the attacker intercept the traffic from the server to the client and change the link to sign in from https://account.google.com"
 to "http://compte.google.com".
* The user browser will make a DNS request to "compte.google.com".
* the attacker intercept the request, make a real DNS request to the real name "account.google.com" and sends back the response "fake domain name + real IP" back to the user.
* When the browser receives the DNS answer, it will search if this domain should be accessed by HTTPS. By checking a Preloaded HSTS list of domains, or by seeing the domain already visited that are in the cache or for the session, dunno. Since the domain is not real, the browser will simply make a HTTP connection the REAL address ip. ==> HTTP traffic at the end

WHEN SSLSTRIP2/DNS2PROXY WORKS ?

Most people never type https://example.com directly. They rely either on links (click _here_ to access our secure login server) or on redirects (type "gmail.com " in the browser, and you will be automatically redirected to a secure site).

This is where SSLStrip comes in: it intercepts the original, unsecured HTTP reply, and replaces <a href="https">; links with HTTP (insecure) versions.

So the real limitations still is that the need for indirect HTTPS links for this to work.

When sslstrip2/dns2proxy. can not work ?

1. when domain is in HSTS preloaded list with "force-https", and "include-subdomains" flags.
    force-https - will make connection https even if user typed
http://domain.com (browser will not wait for server to make connection
secure, it will make it https itself)
    include-subdomains -  with this flag we can say that dns2proxy is
useless. (if domain.com  is HSTS, then with include-subdomains flag
xxxx.domain.com, zzz.xxx.domain.com also are HSTS, so no
benefits to redirect domain to another subdomain)

2. when we have cached 301 redirects. When user types domain.com
the browser tries to query http://domain.com and then is offline
redirected to https://domain.com thru an old cached 301 redirect
(saved on the first access), and this cache does not have an expiry
date. So the only possible solution would be to manually clean caches
on victim's computer.

3. when user directly types domain with https(i.e. https://domain.com)

ABOUT TESTS:

1. typed http://google.com, and it has been successfully redirected to
http://wwww.google.com 
(tested on chrome browser, google.com domains in in HSTS list but
without force-https flag)

2. typed https://google.com, no redirection, got warning message,
(tested on chrome browser, google.com  domains in in HSTS list but
without force-https flag)

3. typed http://gmail.com, redirected to https://gmail.com (by
browser) and got warning page 
(tested on chrome browser, domain gmail.com  is in HSTS list with
force-https flag)

4. typed http://gmail.com in chromium browser, redirected to
http://cuentas.google.com, page was successfully opened. 
(tested on chromium browser witch do not have hsts preloaded list).

Conclusion:

if domain typed directly with https: (i.e. https://domain.com), no
matter your domain is HSTS or not it will fail
if domain typed with http: (i.e. http://domain.com) if domain is in
HSTS list with force-https flag it will fail, if no flag it will be
successfully opened.

HOW TO BYPASS HSTS ?

At this moment I can suggest to
1. use our browser
2. use browser with no HSTS list(like chromium in linux)
3. disable HSTS checking in user's browser
4. add CA in user's browser

I think any HSTS bypassing solution will be immediately fixed by
security team, as now dns2proxy solution is fixed by
include-subdomains flag in HSTS preloaded list, So all this opensource
solutions are temporary, we need to think about something permanent.

**Comment by nikdavnik** [comment]
As we decided to use our browser, this issue can be closed.

**Comment by nikdavnik** [comment]
Yhis issue is not actual anymore and can be closed

**Comment by orwellencarnation** [comment]
This works downgrading the https to http
https://github.com/Librerouter/Librekernel/blob/gh-pages/hsts-bypass
After we need a redirection after the downgrading transparently for the browser.
Huge technical investigation and probably coding is required in different tools
