### ISSUE TITLE
Search engine embed in the browser problem direct browser writing

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#19]
When you write in the browser directly google or skype or what ever the redirection of yacy and replacing the local search engine in the browser to yacy do not work and its very related in some use cases with HSTS

**Comment by nikdavnik** [comment]
In many browsers default search engine is set to https://www.google.com
So when you type something to search, browser will try to connect to https://www.google.com and because google.com is HSTS redirection to yacy is not working.

I disabled HSTS checking in firefox browser and default search redirection to yacy worked. 
So this issue will be fixed once we find a way for HSTS redirection.

Another solution for this is to create a domain certificate for google.com domain (in yacy) and install CA in browser. (this is tested for HSTS gmail.com)

**Comment by mogolo** [comment]
This is not true, its redirected to yacy but the google query is not the same in yacy that in google
so simply WONT WORK!
, you need to do url rewrite rules to convert a google query to a yacy query

**Comment by nikdavnik** [comment]
I added rule to rewrite google's search to yacysearch.html, but also there
is a need to pass search parameter whitch are different for google and
yacy. will continue to work on it.
