### ISSUE TITLE
Urgent for Joakin Ciruitos CPU temperature warnings in setup.sh plus force screen never standby

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#253]
Need to be implemted, in the Setup.sh and need to be disabled witout the required to reboot the machine

**Comment by JFrancoJ** [comment]
About thermal throttling CPU messages, are two possible causes:
1. Is due because /sys/device/system/cpu/cpu1/cpufreq/scaling_governor is setted to powersave
or 
2. Is due really the CPU temp comes too high

Fixing this issue requires to change the scaling_governor values AND test for real CPU temperature.

Moving out all Kernel ( even enabled in BIOS ) thermal throttling can cause CPU comes damaged !!!

**Comment by JFrancoJ** [comment]
About screen blanking, I will add "setterm -blank 0" on top of setup.sh to avoid console comes blank due powersaving

**Comment by JFrancoJ** [comment]
apt-get install cpupower
cpupower frequency-set -g performance  # before was powersave

**Comment by JFrancoJ** [comment]
Added to app-installation-script.sh 
Now console must not be blanked
Temperature throttle is EXPERIMENTAL and requires monitoring to come sure changing from powersave to performance governance mode fix the issue.
The kernel/BIOS message is not due to ,high temperature , but powersave governance. Tested with CPU's at 37ªC - 38ªC

**Comment by orwellencarnation** [comment]
Can the outpunt print of the temperature disabled?

**Comment by Dmitry36** [comment]
image for CPU temperature issue 
![0-weu-d2-4106278e8195718b841f5279fd172271](https://cloud.githubusercontent.com/assets/26918931/24746037/53b6029c-1aea-11e7-82f8-d9058f31ed12.jpg)
