### ISSUE TITLE
Joakin Setup git not able to report if something fail because git ...

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#275]

**Comment by JFrancoJ** [comment]
For now the reports are uploaded to github once at the end of setup.sh and after app-installation-script.sh and  have been completed ( even with some errors )
But if the errors affects the installation of git itself or other critical packets then the report fails.
The solution may be to install in Debian installation, i.e. from preseed.conf at least rsync or ftp, and then upload these reports even other things fails in setup.sh

**Comment by JFrancoJ** [comment]
Waiting for ISO and how we are going to install Debian and installation. Until we have not a clear idea if we put the low dependency procedure to complete the reports, if put in Debian itself ( thanks to preseed ) or in first line of setup.sh and then not requiered on preseed.
I asked this same question several times to you and to Joakin, if he was going to add apt-get in preseed or not.
Second, if we use no git, we can use ftp, rsync or other ways, and we need to define what of them and where to send the reports instead github, since git failed due installation errors.
