### ISSUE TITLE
URGENT JOAKIN FRANCO : WIZZARD path and execution is not in implemented

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#281]
#wi...tab tab nothing
wizard path or script is not in place from latest setup installed 6th april

You should implement in setup.sh to download and install the wizzard to be executable.

**Comment by JFrancoJ** [comment]
See line 90 of setup.sh, I already did the comit 9 days ago to copy the wizard.sh to /root/libre_scripts/.

**Comment by orwellencarnation** [comment]
Not working, wizzard cnat be directly excuted from shell and this installation is fresh 2 days ago made.

**Comment by JFrancoJ** [comment]
The setup.sh just DOWNLOAD the wizard.sh, don't call it.
If you want wizard.sh automatic be executed on next boot we need to 
place a init.d to be called just once
on next boot. This must be placed at the end of configuration to be done 
only in next boot ... or until the
user change his password ( forced to change the passwd, otherwise the 
wizarsh will be launched on each
boot ). I like until user change at least his password.

Pls. check you already have the /root/libre_scripts/wizard.sh and is 
executable.


orwellencarnation wrote:

**Comment by JFrancoJ** [comment]
Fixed in setup.sh commit
