### ISSUE TITLE
Step 8 in app installation script

### ISSUE THREAD

**Issue by pastafaarian** [Librerouter/Librekernel#56]
- Step 8 Required (not implemented)
Setup the propper exit for the script with a propper succes or not
Success need to be based in a list check for all apps has being installed.
Example by checking new directories, config files or other changes in the system

**Comment by petrskovoroda** [comment]
Error checking is implemented in commit 18c079bb4e125d3fd5b8234b817b5ea50afb2db1
It guarantees that everything was installed successfully.
Checking every application is not necessary. Not everything could be run with -v or -h options, and even if it does and executes correctly, you don't know, if it won't crash with segfault later.
But this might happen only after building application from scratch, and since we get most of the packages from official Debian repositories, we can be sure, that everything works.
So, I think, installation checks should be enough.
