### ISSUE TITLE
Installation script hangs

### ISSUE THREAD

**Issue by dbavale** [Librerouter/Librekernel#76]
Installation script hangs while executing and stops at "Installing bridge-utils".

**Comment by SibirskiyVolk** [comment]
please provide the output of:
`cat /tmp/apt-get-install-bridge.log`

**Comment by dbavale** [comment]
Reading package lists...
Building dependency tree...
Reading state information...
Package bridge-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by dbavale** [comment]
I guess after configuring source.lists the scripts start working...

**Comment by SibirskiyVolk** [comment]
This doesn't happen in the iso as the repositories come preconfigured by the build scrips at the build time.

I have another issue with the installation script with the GTK installer that I built for the system, as the script hangs during the installation of the dependencies before the services installation. it causes the UI to hang ... I suspect this is related to debconf waiting for user input although it's supressed. will try the latest build that I am downloading now, and open another issue if it still exists.

Can we have an IRC channel so that we can ease up the communication ?!

**Comment by dbavale** [comment]
Can we communicate using skype?

**Comment by orwellencarnation** [comment]
david update on this
